import type { Metadata } from "next";
import { Inter } from "next/font/google";
import globalCSS from "./global.module.css";
import GlobalTheme from "@/theme/globalTheme";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: RootLayout) {
  return (
    <html lang="en">
      <body className={`${font.className} ${globalCSS.body}`}>
        <GlobalTheme>
          {props.auth}
        </GlobalTheme>
      </body>
    </html>
  );
}


export type BaseLayout = {
  children: React.ReactNode
}

type RootLayout = BaseLayout & {
  admin: React.ReactNode
  auth: React.ReactNode
  user: React.ReactNode
}